### PR TITLE
(Minor, before release) Script to configure github quickly

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Don't know if this is a desired thing in contrib.

I found its a pain to have to configure my git hub identity on the pi every time i rebuild it so i can commit changes.

Script sets up your git environment so you can push changes from the pi.

👍  or 👎 

*note* CI showing unrelated error

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
Idk how much I'll use it, but there's no harm, especially because it's in contrib.

**Comment by darkdrgn2k** [comment]
> Idk how much I'll use 

if you want to git commit/push right from the pi you need to set these variables

**Comment by makeworld-the-better-one** [comment]
Ok, sure. Let's merge.

**Comment by benhylau** [comment]
Either merge or close this?

**Pull request merged**
